server:
  port: 8085

spring:
  application:
    name: workflow-service
  config:
    import:
      - optional:nacos:workflow-service.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.184.100:8848
        namespace: public
        group: DEFAULT_GROUP
      config:
        server-addr: 192.168.184.100:8848
        file-extension: yaml
        namespace: public
        group: DEFAULT_GROUP
        refresh-enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.184.100:3306/workflow?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true
    username: root
    password: "Root@123456"

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.central.workflow.entity
  configuration:
    map-underscore-to-camel-case: true

# Flowable配置
flowable:
  database-schema-update: true
  async-executor-activate: false
  job-executor-activate: false
  flowable-ui-common-enabled: false
