server:
  port: 8081

spring:
  application:
    name: sale-service
  config:
    import:
      - optional:nacos:sale-service.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.132.100:8848
        namespace: public
        group: DEFAULT_GROUP
      config:
        server-addr: 192.168.132.100:8848
        file-extension: yaml
        namespace: public
        group: DEFAULT_GROUP
        refresh-enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.132.100:3307/sale?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: "Root@123456"
  data:
    redis:
      host: 192.168.132.100
      port: 6379
      password: 123456
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.central.sale.entity
  configuration:
    map-underscore-to-camel-case: true
