server:
  port: 8083

spring:
  application:
    name: flow
  datasource:
    url: jdbc:mysql://localhost:3306/flow?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  sql:
    init:
      mode: always

# Flowable 配置
flowable:
  database-schema-update: true
  process:
    def:
      cache:
        enabled: true